
server:
  port: 8081

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/userservice
    username: postgres
    password: postgres

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

jwt:
  secret: NzhkYjM0N2E2ZDYyNzA3NzJlMjU4YTI2NDM5MGE0NGU2ZDE2NDM3Y2M2YjE5MWE3N2U1YWM5NzE4ZGIwZDYwYg==
  expiration: 86400000
  refresh-token-expiration: 600000

rate:
  limit:
    capacity: 10
    refill-minutes: 1
