
server:
  port: 8081

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/userservice
    username: postgres
    password: postgres

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

jwt:
  secret: bXlzdXBlcnNlY3JldGtleQ==
  expiration: 86400000
  refresh-token-expiration: 600000

rate:
  limit:
    capacity: 10
    refill-minutes: 1
